language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: y/1JZvchqwzLyEr6gE3bDjtxiPmX6YKyhPICfbwapfu72/sJJarPDxcNgLPg+rCT9SWUrcdCNPpTtWknyyQ1kOEJjRvOs0ft8RiK1mE9T3a7TsJl9Ws945RwWbsztDpbR5ibPpRo63LiCZGZLY156zEl63BtLsDcWOS34KxWfB8ODjTuwvLKRrtA3TGQu6S+mVx9GLpULBWxjJ3oFN1a9HRxqMa1sYp5lOUvXI4NwR/cScbENKNFedug59ZWEU6zPiBXKfFBBbMYeYNT+b5L0GWtlHgq/7vzViFapuPXxmTouMwH60Xma9taJ59F8UyVZdeg82+DaoUifcNnNGJpSeu/4FhwZFom6Ygar3MeVR5zDBoJ/mFpehkbHFLlD7I3K+8GDSpNQtiMNM2rjd3hAmy8vUDabus7vybDm3Bpj0SQGX5ur0h888AFnML3d2rfaZ8xUSrp9ygDeB50TsqVPO0kGhubgtl2yvFKhkjX31u2IZy9oLMfrz1kA3uGyTj/bx/44XLUjuCumWtVpR7YpJdISc/ZxzSv0UQhg27aCfbWC1UvtluP6csEgJ8nIZIQe9bvKJzrjnoM/BbKvFUt+duCl2w3rrIhBvIL3NCp5sXf9TWYUSNfXfYRzRIqJYRPUxuwH2Z7Xp8voUaqWB7vFidXUU24T6Smy7iTjvgv+io=
  app: narwhal-msg-srch-microservice
  on:
    repo: narwhal-chat/narwhal-message-search-microservice
